# Generated by Django 4.2.29 on 2026-03-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clientrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='package',
            field=models.CharField(blank=True, choices=[('express-assistance', 'Express Assistance'), ('basic-application-support', 'Basic Application Support'), ('standard-application-package', 'Standard Application Package'), ('priority-application-package', 'Priority Application Package'), ('general-digital-assistance', 'General Digital Assistance')], max_length=50),
        ),
    ]
