# Generated by Django 4.2.29 on 2026-04-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_clientrequest_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='package',
            field=models.CharField(blank=True, choices=[('express-assistance', 'Express Assistance'), ('basic-application-support', 'Basic Application Support'), ('standard-application-package', 'Standard Application Package'), ('priority-application-package', 'Priority Application Package'), ('general-digital-assistance', 'General Digital Assistance'), ('consultation', 'Consultation'), ('cv-creation', 'CV Creation'), ('travel-documentation-support', 'Travel Documentation Support')], max_length=50),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='service',
            field=models.CharField(choices=[('digital-assistance', 'Digital Assistance'), ('application-support', 'Student Application Support'), ('admission-payment', 'Admission Payment Assistance'), ('cv-review', 'CV Review'), ('portfolio-website', 'Portfolio Website'), ('consultation', 'Consultation'), ('travel-documentation', 'Travel Documentation & Application Support')], max_length=50),
        ),
    ]
